### ISSUE TITLE
SyntaxError when execute gum list

### ISSUE THREAD

**Issue by kkfreedom** [gauseen/gum#1]
Got this issue when execute gum command
![image](https://user-images.githubusercontent.com/37065275/123949827-9cfcb280-d9d5-11eb-9f06-0f3b5ac603ab.png)

npm version: 6.14.12

**Comment by gauseen** [comment]
@kkfreedom 可以将 node 升级为最新稳定版吗？

**Comment by gauseen** [comment]
@kkfreedom 可以安装 @gauseen/gum@1.0.3 版本，本地测试支持 node v9.0.0 及以上版本

**Comment by kkfreedom** [comment]
npm升级到最新版本以后好了👍， thx
