### ISSUE TITLE
Current project not a git repository (or any of the parent directories)

### ISSUE THREAD

**Issue by TenviLi** [gauseen/gum#5]
when use `gum use <group-name> --global `, it must also be in a git repo, or not working

**Comment by TenviLi** [comment]
![image](https://user-images.githubusercontent.com/30214981/128967526-0ee36be0-34d4-4bbb-95ea-63eb03f61b49.png)

**Comment by gauseen** [comment]
@gylidian You can update to v1.0.5

**Comment by TenviLi** [comment]
> @gylidian You can update to v1.0.5

@gauseen thanks for your reply
