### ISSUE TITLE
能否支持修改group-name呢？ Can gum support group-name modification？

### ISSUE THREAD

**Issue by Likenttt** [gauseen/gum#8]
如题，我知道可以删除需要重命名的组然后重建，但是我只是想改一个名字而已，不想删除.
As the title, I know there is a workaround，ie delete the group that need to be renamed and reconstruct it. But I just wanna modify the name rather than delete it.

**Comment by Likenttt** [comment]
另一个workaround：直接编辑 .gumrc

**Comment by gauseen** [comment]
@Likenttt 这个场景应该很少吧，暂时没考虑支持
